# Generated by Django 2.2.7 on 2020-09-07 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='creat_time',
            new_name='create_time',
        ),
    ]
