# Generated by Django 3.2.5 on 2021-08-26 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_user_passwd'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableData',
            fields=[
                ('table_id', models.AutoField(primary_key=True, serialize=False)),
                ('table_name', models.CharField(max_length=50)),
                ('table_data', models.JSONField()),
            ],
        ),
    ]
